### Site Settings ###
title               : Li-Wei Yang
description         : I am migrating my personal website to gitlab.io for better jekyll support. <br>
                      Please move to the <a href="https://liver121888.gitlab.io/">new website</a> for better experience. <br>
baseurl             : "" # Change to empty quotes if you are hosting your site at <your-username>.github.io directly
repository          : liver121888/liver121888.github.io # Change to <your-username>/<your-username>.github.io (or remove it if you don't need remote projects)
remote_theme        : YoussefRaafatNasry/portfolYOU
open_new_tab        : false # Opens external URLs in new tab (works for posts, projects and navbar only)


### Plugins ###
plugins:
  - jemoji
  - jekyll-pdf-embed


### Navbar Settings ###
nav_exclude: # The following paths are excluded from navbar
  - pages/tags.html
  - pages/tools.html
  - pages/404.html
  - pages/index.md


### Author Info ###
author:
  name              : Li-Wei Yang
  image             : img/profile.jpg
  linkedin          : dancedfsk8
  email             : liver121888@gmail.com
  github            : liver121888
  youtube           : david121888
  medium            : liver121888
  facebook          : david121888
  instagram         : liver_1218
  kaggle            : b07611001
  gitlab            : liver121888
  stackoverflow     : 15630120
  twitter           : yumhxAZJkEOjMHZ
  # behance           : your_username
  # dribbble          : your_username
  # soundcloud        : your_username
  # spotify           : your_username
  # tumblr            : your_username.tumblr.com
  # twitch            : your_username
  # vimeo             : your_username
  # keybase           : your_username


### Posts ###
permalink: /blog/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name



### Disqus ###
disqus:
  shortname: liver121888 # Your website Shortname on disqus


### Analytics ###
analytics:
  enabled: true # Set true to enable analytics
  google:
    tracking_id: G-KF4ZYPGYNN


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "projectpage"
  - scope:
      path: ""
      type: "posts"
    values:
      comments: false # Set to true to enable disqus comments


### Exclude from processing ###
exclude:
  - README.md
  - LICENSE
  - "*.log"
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
github: [metadata]